import random
import time
print("There are 103680 combonations")
x = ("Correct", "Incorrect")
print("")
print("")
print("")
one = ("True or False,", "Multiple choice,", "Short Answer,")
two = ("how big is the", "how fat is the", "which turtle is the")
three = ("best", "thiccist", "most fiberous", "most explosive")
threetwo = ("color", "butter", "banana", "potato", "purple", "letter", "fruit", "nuclear pasta")
four = ("of the alphabet", "of the food pyramed", "of the universe")
five = ("-True", "-bananas", "-PooPoo", "-Chair", "-Pewdiepie", "-Jeremy Clarkson")
six = ("-Broccoli", "-fishsticks", "-James May", "-Jell-o", "-Sewage")
seven = ("-False", "-A", "-HAMMOND")
time.sleep(5)
while True:
  h = random.randint(0,1)
  a = random.randint(0,2)
  b = random.randint(0,1)
  c = random.randint(0,3)
  ctwo = random.randint(0,7) 
  d = random.randint(0,2)
  e = random.randint(0,5)
  f = random.randint(0,4)
  g = random.randint(0,2)
  print(one[a], two[b], three[c], threetwo[ctwo], four[d])
  time.sleep(2)
  print("")
  print(five[e])
  print("")
  time.sleep(1)
  print(six[f])
  print("")
  time.sleep(1)
  print(seven[g])
  print("")
  time.sleep(1)
  sadness = str(input("Answer: "))
  #if sadness = "potatoes":
  #  h = 0
  print("")
  print("")
  time.sleep(1)
  print(x[h])
  print("")
  print("")
